name: guohuiweb3

on:
  push:
    branches: # 此处不仅限于监听分支, 还可监听 tag
      - main
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      #  检出代码库
      - name: Checkout
        uses: actions/checkout@main

      # 设置Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.1

      # 打包构建
      - name: Build
        run: |
          npm install
          npm run build

      # 上传到服务器
      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          # 拷贝 .next、public文件夹和package.json文件到服务器指定目录
          source: '.vitePress/dist'
          target: '/data/siteWeb3'
