name: guohuiweb3

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      #  检出代码库
      - name: Checkout
        uses: actions/checkout@main

      # 设置Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      # 打包构建
      - name: Build
        run: |
          npm install
          npm run build

      # 上传到服务器
      - name: Upload
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USERNAME }}
          SOURCE: '.vitepress/dist'
          TARGET: '/data/website'
